# Generated by Django 3.2.8 on 2021-10-23 06:08

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=255, verbose_name='Industry title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('skill', models.CharField(max_length=255, verbose_name='Skill')),
                ('skill_type', models.CharField(choices=[('soft', 'Soft Skill'), ('technical', 'Technical Skill')], max_length=20, verbose_name='Skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('posted_date', models.DateTimeField(auto_now_add=True, verbose_name='Posted Date')),
                ('specification', models.TextField()),
                ('no_of_vacancies', models.PositiveIntegerField(default=1, verbose_name='No of Vacencies')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('remote', 'Remote'), ('temporary', 'Temporary'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('traineeship', 'Traineeship'), ('volunteer', 'Volunteer')], default='contract', max_length=20, verbose_name='Employment Type')),
                ('job_education', models.CharField(choices=[('phd', 'Ph.d'), ('master', 'Master'), ('bachelor', 'Bachelor'), ('intermediate', 'Intermediate (+2)'), ('slc', 'Slc (10th)'), ('other', 'Other')], default='bachelor', max_length=50, verbose_name='Education')),
                ('experience', models.CharField(max_length=255, verbose_name='Experience required')),
                ('job_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('top', 'Top Level')], default='entry', max_length=10, verbose_name='Job level')),
                ('is_draft', models.BooleanField(default=True)),
                ('offered_salary', models.CharField(default='Negotiable', max_length=255, verbose_name='Offered Salary')),
                ('what_we_offer', models.TextField(max_length=255, verbose_name='What we offer')),
                ('deadline', models.DateTimeField()),
                ('job_industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='job.industry')),
                ('job_location', models.ManyToManyField(to='job.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
