# Generated by Django 3.2.8 on 2021-11-04 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_method',
            field=models.CharField(default='', max_length=255, verbose_name='Apply method'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_categories', to='job.category'),
        ),
    ]
