# Generated by Django 3.2.8 on 2021-11-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20211104_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='Job description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='no_of_vacancies',
            field=models.PositiveIntegerField(default=1, verbose_name='No of Vacancies'),
        ),
        migrations.AlterField(
            model_name='job',
            name='specification',
            field=models.TextField(verbose_name='Job specification'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Job title'),
        ),
    ]
