# Generated by Django 3.2.8 on 2021-11-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20211104_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_method',
            field=models.CharField(help_text='Send your CV to hr@yourcompany.com or apply through ulike', max_length=255, verbose_name='Apply method'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(help_text='2 year', max_length=255, verbose_name='Experience required'),
        ),
        migrations.AlterField(
            model_name='job',
            name='no_of_vacancies',
            field=models.PositiveIntegerField(default=1, help_text='10', verbose_name='No of Vacancies'),
        ),
        migrations.AlterField(
            model_name='job',
            name='offered_salary',
            field=models.CharField(default='Negotiable', help_text='45K to 75K or Negotiable', max_length=255, verbose_name='Offered Salary'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(help_text='IT manager', max_length=255, verbose_name='Job title'),
        ),
    ]
