# Generated by Django 3.2.12 on 2022-03-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20211121_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', to='job.Skill'),
        ),
    ]
