# Generated by Django 3.2.12 on 2022-03-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('hot_job', 'Hot Job'), ('top_job', 'Top Job'), ('free_job', 'Free Job'), ('feature_job', 'Featured job'), ('newspaper_job', 'NewsPaper Job')], default='top_job', max_length=255),
        ),
    ]
