# Generated by Django 3.2.12 on 2022-04-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20220407_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobappliedbyuser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=255),
        ),
    ]
