# Generated by Django 3.2.8 on 2021-11-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20211121_1823'),
        ('account', '0005_auto_20211123_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_preferences',
            field=models.ManyToManyField(related_name='categories', to='job.Category'),
        ),
    ]
