# Generated by Django 3.2.8 on 2021-11-24 10:44

import datetime
import uuid

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20211121_1823'),
        ('account', '0006_userprofile_job_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='available_for',
            field=models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('remote', 'Remote'), ('temporary', 'Temporary'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('traineeship', 'Traineeship'), ('volunteer', 'Volunteer')], default='contract', max_length=20, verbose_name='Employment Type'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career_objective',
            field=models.CharField(default=datetime.datetime(2021, 11, 24, 10, 43, 10, 590493, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(default=datetime.datetime(2021, 11, 24, 10, 43, 21, 279758, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_address',
            field=models.CharField(default=datetime.datetime(2021, 11, 24, 10, 43, 26, 331783, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='Tick this for any kind of physical disability.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_level',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('top', 'Top Level')], default='entry', max_length=10, verbose_name='Job level'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_preference_location',
            field=models.CharField(default=datetime.datetime(2021, 11, 24, 10, 43, 42, 629645, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='martial_status',
            field=models.CharField(choices=[('married', 'married'), ('unmarried', 'unmarried')], default=datetime.datetime(2021, 11, 24, 10, 43, 49, 381610, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(default='nepali', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permanent_address',
            field=models.CharField(default='jubhung', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(choices=[('Buddhism', 'Buddhism'), ('Sikhism', 'Sikhism'), ('Bahai', 'Bahai'), ('Christianity', 'Christianity'), ('Hinduism', 'Hinduism'), ('Islam', 'Islam'), ('Jainism', 'Jainism'), ('Nonreligious', 'Nonreligious')], default='hindu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='job.Skill'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specializations',
            field=models.CharField(default='devops', help_text='Devops Enginnering', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('organization_name', models.CharField(help_text='Perl Infotech', max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('top', 'Top Level')], default='entry', max_length=10, verbose_name='Job level')),
                ('currently_working_here', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('duties_and_responsibilities', models.TextField()),
                ('nature_of_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='job.industry')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_experiences', to='account.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name_of_training', models.CharField(help_text='Excel training', max_length=255)),
                ('institution_name', models.CharField(help_text='Viat Academy nepal', max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('duration_type', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='account.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('reference_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('organization_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='account.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('language', models.PositiveIntegerField()),
                ('reading', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('writing', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('speaking', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('listening', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages', to='account.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('degree', models.CharField(choices=[('phd', 'Phd'), ('master', 'Master'), ('bachelor', 'Bachelor'), ('intermediate', 'Intermediate'), ('slc', 'SLC (10th)'), ('other', 'Other')], max_length=255)),
                ('education_program', models.CharField(help_text='BSC Computer engineering', max_length=255)),
                ('education_board', models.CharField(help_text='Pokhara University', max_length=255)),
                ('name_of_institue', models.CharField(help_text='Cosmos college', max_length=255)),
                ('started_year', models.DateField()),
                ('current_studying_here', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educations', to='account.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
