# Generated by Django 3.2.12 on 2022-03-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_job_type'),
        ('account', '0007_auto_20211124_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Company Size'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='About company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='established',
            field=models.CharField(max_length=4, null=True, verbose_name='Established date'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(null=True, upload_to='uploads/company/profile'),
        ),
        migrations.AlterField(
            model_name='company',
            name='organization_name',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Organization name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='available_for',
            field=models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('remote', 'Remote'), ('temporary', 'Temporary'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('traineeship', 'Traineeship'), ('volunteer', 'Volunteer')], default='contract', max_length=20, null=True, verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='career_objective',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='Tick this for any kind of physical disability.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_level',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('top', 'Top Level')], default='entry', max_length=10, null=True, verbose_name='Job level'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_preference_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_preferences',
            field=models.ManyToManyField(null=True, related_name='categories', to='job.Category'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='martial_status',
            field=models.CharField(choices=[('married', 'married'), ('unmarried', 'unmarried')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='permanent_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/user/profile', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(choices=[('Buddhism', 'Buddhism'), ('Sikhism', 'Sikhism'), ('Bahai', 'Bahai'), ('Christianity', 'Christianity'), ('Hinduism', 'Hinduism'), ('Islam', 'Islam'), ('Jainism', 'Jainism'), ('Nonreligious', 'Nonreligious')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(null=True, related_name='skills', to='job.Skill'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specializations',
            field=models.CharField(help_text='Devops Enginnering', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
