# Generated by Django 3.2.12 on 2022-03-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20220330_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default='1990-05-02'),
            preserve_default=False,
        ),
    ]
