# Generated by Django 3.2.12 on 2022-04-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_userprofile_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.PositiveIntegerField(max_length=10, null=True),
        ),
    ]
